### ISSUE TITLE
new spgram

### ISSUE THREAD

**Issue by haniov** [avl-ttu/QuailKit.m#3]
@bozingle so there is 2 new m files:
HTstpsd and HTstpsd_example

the example file shows how to use it to create spgrams for specific intervals. this implementation takes care of the spectrogram shortness and longness so if you use it as in example it will give you exact same interval including interval edges. so you can tile the 40 seconds intervals with peace of mind (of course skipping the single edge sample that is repeated between neighboring intervals.) since the first and last interval for the whole audio doesn't have any space to compensate for spectrogram shortening effect (there is no time negative or larger than the last second recorded) you have to repeat the first 1/spgramfs seconds and the last 1/spgramfs enough so it will cover the empty spaces in our case the first 0.04 (starting from 0) and the last 0.04 (ending with last time value avalable in original signal that is dividable by 1/sampling-freq-of-spgram) . this way later on while reconstruction the t we will have less nonsense. by the way use the same formula that is in jr_data to reconstruct t and make sure python is doing the exact same thing.

- [ ] use the new htspgram file to tile spgrams into h5 files. second zero to last.

- [ ] use the resulting props structure to write attributes in h5 spgram datastore (same name and value).

- [ ] I got rid of the normalization so please get rid of raw. now audio should be the raw audio signal without any zscore function written to h5 files.

- [ ] update the python to read from new files accordingly.

see if you still can not create branches from master inside the repo and let me know.

**Comment by Hanif-Tiznobake** [comment]
1. why are you doing this? line 47: `interval = [k-seconds+1,k];` this will ignore the first second of every 40 seconds.
2. why are you doing this? line 46: `k = 40:seconds:audioLength` if you are getiing seconds as input then what is that 40 seconds?
3. why are you doing this? line 61: `h5writeatt(obj.filepath, "/c"+string(num2str(i))+"/spgram", 'props', [props.fs props.freqs]);` you were supposed to write all props values as attributes, that's what it's for.
4. I still am not seeing anything representing repeating data in the missing initial and final 0.04s gap
5. You where supposed to get read of normalization I still see you're processing audio before using it in line 32. get rid of process and read methods. read directly  and don't process.

I don't wanna go through your code line by line. in that case it will be faster if I do it myself. please correct it asap. I didn't check your the python repo but I can assume in needs work also. and stop checking to do list while you're clearly not done with them.

**Comment by Hanif-Tiznobake** [comment]
@bozingle the sampling problem is solved now. there shouldn't be any corner cases and the sampling must start at t0 with the sampling frequency of spgramfs consistently throughout the spgram with only one sample overlap on neighbouring intervals. run the updated HTstpsd_example for clarification and let me know is something looks funny or you have any questions. branch out of the master branch and do the rest of the above. tiling, etc.. thanks.

**Comment by Hanif-Tiznobake** [comment]
@bozingle 
- you're not using you're emptyfile method as a result I had to get rid of h5 files recreate them and run the software for detection again.
- you're also not removing the last sample of each chunk, remember? one sample overlap?
- it still doesn't check for specific dataset with the same props.

**Comment by Hanif-Tiznobake** [comment]
@bozingle I will take care of this myself. I didn't want to get involved in the h5 things but now i am so I might as well do it myself. another task is coming, get ready
